project_name: kube-score
version: 2

builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - amd64
  dir: cmd/kube-score

archives:
  - id: binary
    format: binary
    files:
      - LICENSE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc

release:
  github:
    owner: cloudogu
    name: kube-score
  name_template: 'v{{ .Version }}'
  header: 'Release generated at commit: {{ .ShortCommit }}'
  draft: true
  replace_existing_draft: true
