name: Test Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
          cache-dependency-path: 'go.sum'

      - name: Test
        run: go test -v ./...

      - name: Build
        run: CGO_ENABLED=0 go build -o kube-score ./cmd/kube-score

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          name: '${{ github.ref_name }}'
          body: 'Release generated at commit: ${{ github.sha }}'
          files: kube-score
